language: python
python:
  - "3.7"
before_install:
    - pip install pep8
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python tests.py
  - find . -name \*.py -exec pep8 {} +